#
# Module manifest for Standby DB management module
#
# Generated by: Kirill Kravtsov
#
# Generated on: 1/13/2017
#
@{

    # Script module or binary module file associated with this manifest.
    ModuleToProcess        = 'SQLDBMgmt.psm1'

    # Version number of this module.
    ModuleVersion          = '0.1'

    # ID used to uniquely identify this module
    GUID                   = 'F474847C-5883-44D8-A001-656DB9FBE28F'

    # Author of this module
    Author                 = 'Kirill Kravtsov'

    # Company or vendor of this module
    CompanyName            = ''

    # Copyright statement for this module
    Copyright              = '2017 Kirill Kravtsov'

    # Description of the functionality provided by this module
    Description            = 'Introduces procedures to control the creation and maintenance of SQL Server databases and performing restore operations.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion      = '2.0'

    # Name of the Windows PowerShell host required by this module
    PowerShellHostName     = ''

    # Minimum version of the Windows PowerShell host required by this module
    PowerShellHostVersion  = ''

    # Minimum version of the .NET Framework required by this module
    DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    CLRVersion             = ''

    # Processor architecture (None, X86, Amd64, IA64) required by this module
    ProcessorArchitecture  = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules        = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies     = @('Microsoft.SqlServer.Smo', 'Microsoft.SqlServer.SmoExtended')

    # Script files () that are run in the caller's environment prior to importing this module
    ScriptsToProcess       = @()

    # Type files (xml) to be loaded when importing this module
    TypesToProcess         = @()

    # Format files (xml) to be loaded when importing this module
    FormatsToProcess       = @()

    # Modules to import as nested modules of the module specified in ModuleToProcess
    NestedModules          = @()

    # Functions to export from this module
    FunctionsToExport      = @(
        'Copy-SQLDatabaseOffline',
        'Copy-SQLDBProperties',
        'New-DBConnection',
        'New-SMOConnection'
    )

    # Cmdlets to export from this module
    CmdletsToExport        = '*'

    # Variables to export from this module
    VariablesToExport      = '*'

    # Aliases to export from this module
    # Aliases are stored in dbatools.psm1
    AliasesToExport        = @()

    # List of all modules packaged with this module
    ModuleList             = @()

    # List of all files packaged with this module
    FileList               = ''

    PrivateData            = @{}
}